
const elementos1 = document.getElementById('lista-1');
const lista = document.querySelector("#lista-salir tbody");


function leerDatosElemento(elemento){
    const infoElemento = {
        imagen: elemento.querySelector('img').src,
        titulo:elemento.querySelector('h3').textContent,
        precio: elemento.querySelector('.precio').textContent,
        id: elemento.querySelector('a').getAttribute('data-id')
    }
    insertarCarrito(infoElemento);
}


function eliminarElemento(e){
    e.preventDefault();
    let elemento,
        elementoId;
    if(e.target.classList.contains('borrar')){
        e.target.parentElement.parentElement.remove();
        elemento = e.target.parentElement.parentElement;
        elementoId = elemento.querySelector('a').getAttribute('data-id');
    }
}

  var swiper = new Swiper('.swiper-container', {
    slidesPerView: 3,
    spaceBetween: 30,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    autoplay: {
      delay: 2500,
      disableOnInteraction: false,
    },
    loop: true,
  });

  document.addEventListener('DOMContentLoaded', function() {
    const supermercados = {
        ara: {
            ciudades: {
            "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        },
        d1: {
            ciudades: {
                "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        },
        jumbo: {
            ciudades: {
                "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        },
        olimpica: {
            ciudades: {
                "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        },
        exito: {
            ciudades: {
                "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        },
        isimo: {
            ciudades: {
                "Antioquia-Apartado": [" Carrera 108 "],
            "Antioquia-Arboletes": [" Calle 30 # 30-11 "],
            "Antioquia-Carepa": ["Cl. 77 #78a-8 a 78a-104"],
            "Antioquia-Caucasia": ["Carrera 3 A # 9A-34 "],
            "Antioquia-Chigorodo": ["Carrera 98 #92-57 "],
            "Antioquia-Tamesis": ["Calle 11 #9-1"],
            "Antioquia-Turbo": ["Carrera 14 N° 102-69 Imperio 0663 "],
            "Atlántico-Baranoa": ["Calle 17 #18 - 02 "],
            "Atlántico-Barranquilla": ["Calle 30 # 30-11 "],
            "Atlántico-Campo de la cruz": ["Calle 9 #9 - 85"],
            "Atlántico-Galapa": ["Calle 10 #21 - 133"],
            "Atlántico-Juan De Acosta": ["Calle 7 #3 - 81"],
            "Atlántico-Luruaco": ["Carrera 20 # 15 B- 27"],
            "Atlántico-Malambo": ["Carrera 8 # 10-30"],
            "Atlántico-Manati": ["Calle 8 #7-50"],
            "Atlántico-Palmar de Varela": ["Calle 11 # 6 - 03"],
            "Atlántico-Polonuevo": ["Calle 3 # 10 A - 07"],
            "Atlántico-Ponedera": ["Calle 18 #14 - 1"],
            "Atlántico-Puerto Colombia": ["Calle 7 #10-014"],
            "Atlántico-Repelon": ["Calle 8 #10 - 148"],
            "Atlántico-Sabanagrande": ["Calle 11 #85 7"],
            "Atlántico-Sabanalarga": ["Sabanalarga-Manatí #1377"],
            "Atlántico-Santo Tomas": ["a 4d-74, Calle 11b #4d2"],
            "Atlántico-Soledad": ["CR 17AN n° 9A-23"],
            "Atlántico-Suan": ["Calle 3 # 12 - 07"],
            "Bolivar-Arjona": ["a 56-105, Carrera 46b #56-1"],
            "Bolivar-Calamar": ["Calle 19 #2 - 34"],
            "Bolivar-Cartagena": ["Calle 15 #82 - 58"],
            "Bolivar-El Carmen De Bolivar": ["Carrera 63 #22 - 103"],
            "Bolivar-Magangue": ["Avenida 5, Calle 5 #5 - 44"],
            "Bolivar-Maria La Baja": ["Carrera 15 # 10 - 84"],
            "Bolivar-San Jacinto": ["Carrera 41 #23-56"],
            "Bolivar-San Juan Nepomuceno": ["Calle 11 # 11-22 Esquina., san juan centro."],
            "Bolivar-Santa Rosa": ["Calle 16 # 27 - 55"],
            "Bolivar-Turbaco": ["Carrera 7 #3-1 a 3-201"],
            "Boyaca-Chiquinquira": ["Carrera 9 # 10 - 56"],
            "Boyaca-Duitama": ["Calle 18 #5-71"],
            "Boyaca-Garagoa": ["Carrera 15 # 9 - 42"],
            "Boyaca-Guateque": ["Carrera 15 # 9 - 42"],
            "Boyaca-Moniquira": ["Carrera 5 #18 - 27"],
            "Boyaca-Nobsa": ["Carrera 10 #5-26"],
            "Boyaca-Paipa": ["Carrera 21 # 24 - 24"],
            "Boyaca-Puerto Boyaca": ["Puerto Boyacá, Boyacá, Colombia"],
            "Boyaca-Ramiriqui": ["Calle 7 ##507"],
            "Boyaca-Samaca": ["Calle 6 # 4-25"],
            "Boyaca-Santa Rosa De Viterbo": ["Calle 9 # 4 - 24"],
            "Boyaca-Sogamoso": ["Calle 13 #10 – 45/47"],
            "Boyaca-Tunja": ["Carrera 6 # 64B-35"],
            "Boyaca-Villa De Leyva": ["Carrera 9 #9 - 61"],
            "Caldas-Anserma": ["Carrera 4 # 10 - 30"],
            "Caldas-Aranzazu": ["Carrera 5 #6 - 12"],
            "Caldas-Belalcazar": ["Carrera 4 #15-20"],
            "Caldas-Chinchina": ["Calle 13"],
            "Caldas-La Dorada": ["Calle 47"],
            "Caldas-Manizales": ["Calle 21 # 17-26"],
            "Caldas-Neira": ["Calle 10 #71 a 7-67"],
            "Caldas-Palestina": ["Calle 8 #11 - 35"],
            "Caldas-Riosucio": ["Carrera 8 # 10 - 25"],
            "Caldas-Salamina": ["Carrera 6 #7-65"],
            "Caldas-Supia": ["Calle 35 #No 8 - 20"],
            "Caldas-Villamaria": ["CR 17AN n° 9A-23"],
            "Caldas-Viterbo": ["Carrera 7 #9 - 10"],
            "Cesar-Bosconia": ["Avenida 5, Calle 5 #5 - 44"],
            "Cesar-Valledupar": ["Avenida Salguero #28-1"],
            "Cordoba-Ayapel": ["Transversal 7A # 6 - 86"],
            "Cordoba-Cerete": ["Carrera 15 #9A-47"],
            "Cordoba-Chinu": ["Carrera 13 #21-18"],
            "Cordoba-Cienaga De Oro": ["Calle 6 #14-47"],
            "Cordoba-Lorica": ["Avenida 5, Calle 5 #5 - 44"],
            "Cordoba-Momil": ["Calle 7 #11-15"],
            "Cordoba-Montelibano": ["Calle 17a #5-1"],
            "Cordoba-Monteria": ["Calle 29 Carrera 4 # 4-08 Lote A - B Chuchurribi"],
            "Cordoba-Planeta Rica": ["Calle 17 # 7-48"],
            "Cordoba-Sahagun": ["Carrera 14 #19A-6"],
            "Cordoba-San Andres De Sotavento": ["Carrera 7e #7C - 33"],
            "Cordoba-San Antero": ["San Antero, Córdoba, Colombia"],
            "Cordoba-San Bernardo Del Viento": ["Calle 9 # 6-60"],
            "Cordoba-San Pelayo": ["Calle 6 #6 - 10"],
            "Cordoba-Tierralta": ["Calle 10 #16-84"],
            "Cundinamarca-Agua De Dios": ["Carrera 9 #11 - 17"],
            "Cundinamarca-Anapoima": ["Avenida 1 #3-42"],
            "Cundinamarca-Anolaima": ["Calle 4 #3 - 05"],
            "Cundinamarca-Apulo": ["Calle 9 # 4 - 30/34"],
            "Cundinamarca-Bogota": ["Carrera 10 # 15-54"],
            "Cundinamarca-Bojaca": ["Carrera 7 #7-20"],
            "Cundinamarca-Cajica": ["Calle 7 #7-04E"],
            "Cundinamarca-Chia": ["Carrera 5 B # 1A - 79 Mz C LT 26"],
            "Cundinamarca-Choconta": ["Avenida 1 #3-42"],
            "Cundinamarca-Cota": ["Autop Medellin Km 3.9 Costado Sur Zuca Plaza"],
            "Cundinamarca-El Rosal": ["Carrera 3a #8-82"],
            "Cundinamarca-Facatativa": ["Calle 25 C Este #2-18"],
            "Cundinamarca-Funza": ["Calle 15 #15-35"],
            "Cundinamarca-Fusagasuga": ["Cra. 74 #76-24, Fusagasugá"],
            "Cundinamarca-Gachancipa": ["Calle 5 #2-81"],
            "Cundinamarca-Girardot": ["Carrera 10 #13-41"],
            "Cundinamarca-Guaduas": ["Calle 3 53, # 4"],
            "Cundinamarca-Guasca": ["Carrera 4 #3-81 a 3-75"],
            "Cundinamarca-La Calera": ["# a 2b-80, Cl. 7 #22"],
            "Cundinamarca-La Mesa": ["Calle 8 # 17-98"],
            "Cundinamarca-La Vega": ["Carrera 4 #9-87"],
            "Cundinamarca-Madrid": ["Calle 23 #12 129 local 15"],
            "Cundinamarca-Mesitas Del Colegio": ["Calle 10 #5 - 52"],
            "Cundinamarca-Mosquera": ["Carrera 3 #1312"],
            "Cundinamarca-Nemocon": ["Diagonal 2 N° 2 - 35, Zipaquirá-Nemocó"],
            "Cundinamarca-Pacho": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Puerto Salgar": ["a 16-46, Calle 8 #16-18"],
            "Cundinamarca-Ricaurte": ["Calle 10 # 5-215"],
            "Cundinamarca-Sibate": ["Carrera 7 #8-02"],
            "Cundinamarca-Soacha": ["Carrera 4 # 7 - 51"],
            "Cundinamarca-Sopo": ["Carrera 3 # 2-28 Sur"],
            "Cundinamarca-Subachoque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Suesca": ["Calle 8 #4-39"],
            "Cundinamarca-Tabio": ["Diagonal 7 #1 - 89 A"],
            "Cundinamarca-Tenjo": ["Carrera 2 #5-79"],
            "Cundinamarca-Tocaima": ["Frutería Express, Calle 4 #8 - 30"],
            "Cundinamarca-Tocancipa": ["Anillo Vial Verganzo"],
            "Cundinamarca-Ubaque": ["Calle 3 # 3 - 32"],
            "Cundinamarca-Villapinzon": ["Carrera 5 # 3-34"],
            "Cundinamarca-Villeta": ["Carrera 5 #3-04"],
            "Cundinamarca-Viota": ["Carrera 10 # 19 - 04"],
            "Cundinamarca-Zipaquira": ["Carrera 10 # 10-36"],
            "Magdalena-Aracataca": ["Carrera 4 #8 - 10"],
            "Magdalena-Ariguani": ["Calle 4 #4A - 09"],
            "Magdalena-Chibolo": ["Carrera 13 # 5 - 42"],
            "Magdalena-Cienaga": ["Calle 20 # 35 - 45 (Locales 1,2 y 3)"],
            "Magdalena-El Reten": ["Carrera 5 # 6 - 02"],
            "Magdalena-Fundacion": ["Carrera 10 #6 - 15"],
            "Magdalena-Pivijay": ["Pivijay-Media Luna #25-04"],
            "Magdalena-Plato": ["Avenida 20 A #23"],
            "Magdalena-Santa Marta": ["Carrera 4"],
            "Meta-Acacias": ["Calle 18 #14-80"],
            "Meta-Cumaral": ["Carrera 20 #10 - 18"],
            "Meta-Granada": ["Carrera 13 #15-104"],
            "Meta-Mesetas": ["Calle 9 #6-32"],
            "Meta-Puerto Lopez": ["Avenida 14 #14-33"],
            "Meta-Restrepo": ["Carrera 20 #10 - 18"],
            "Meta-San Martin": ["Calle 9 #4-46"],
            "Meta-Villavicencio": ["Villavicencio-Restrepo"],
            "Norte De Santander-Cucuta": ["Avenida 0 #66"],
            "Quindio-Armenia": ["Cra. 19 #35 Norte-623 a 35 Norte-377"],
            "Quindio-Calarca": ["Avenida Colón"],
            "Quindio-Circasia": ["Carrera 15 #6-54"],
            "Quindio-Filandia": ["Calle 7 #5-24"],
            "Quindio-La Tebaida": ["Carrera 6 #No 11 - 69"],
            "Quindio-Montenegro": ["Carrera 5 #1741"],
            "Quindio-Quimbaya": ["Carrera 5 #15-27"],
            "Risaralda-Apia": ["Calle 8 #8 - 19/29"],
            "Risaralda-Belen De Umbria": ["Carrera 11 # 4-33"],
            "Risaralda-Dosquebradas": ["Calle 15 #8A-05"],
            "Risaralda-La Virginia": ["Carrera 5a #12A-45"],
            "Risaralda-Marsella": ["Calle 9 No 10 - 40"],
            "Risaralda-Pereira": ["Calle 75, Barrio 2.500"],
            "Risaralda-Quinchia": ["Carrera 9"],
            "Risaralda-Santa Rosa De Cabal": ["Antigua cooperativa, Calle 14 #11-26"],
            "Risaralda-Santuario": ["Calle 7 #6 - 58"],
            "Santander-Barbosa": ["Carrera 9 # 10 62"],
            "Santander-Barrancabermeja": ["Carrera 20 #54-27"],
            "Sucre-Corozal": ["Calle 40 # 19E- 19, Troncal Ceibol"],
            "Sucre-Coveñas": ["Avenida 5, Calle 5 #5 - 44"],
            "Sucre-Galeras": ["Calle Concepción # 12A - 41, (Galeras centro calle 1111)"],
            "Sucre-Ovejas": ["Carrera 15 #20 - 25"],
            "Sucre-Sampues": ["Carrera 20 #23-38 #23110"],
            "Sucre-San Luis De Since": ["Calle 8"],
            "Sucre-San Marcos": ["Carrera 24 # 24-19"],
            "Sucre-San Onofre": ["Carrera 19"],
            "Sucre-San Pedro": ["Carrera 9"],
            "Sucre-Santiago de Tolu": ["Carrera 2 #14-92"],
            "Sucre-Sincelejo": ["Carrera 17 #11 - 93"],
            "Tolima-Armero": ["Carrera 7 # 6 - 79"],
            "Tolima-Carmen De Apicala": ["Calle 1 # 9A - 07"],
            "Tolima-Chaparral": ["Carrera 9"],
            "Tolima-Espinal": ["Carrera 4 #8 - 31"],
            "Tolima-Flandes": ["Flandes, Tolima, Colombia"],
            "Tolima-Fresno": ["Carrera 7 #6 - 05"],
            "Tolima-Guamo": ["Calle 11 #11 - 46"],
            "Tolima-Honda": ["Calle 9 #N° 19 - 39"],
            "Tolima-Ibague": ["Avenida Guabinal Mz 1 CL 53 y CR 9B"],
            "Tolima-Lerida": ["Lerida, Lérida, Tolima, Colombia"],
            "Tolima-Libano": ["Carrera 10 # 4 - 48"],
            "Tolima-Mariquita": ["Carrera 4 #6 - 66"],
            "Tolima-Melgar": ["Calle 7 #26-39"],
            "Tolima-Ortega": ["Calle 6 #8-09"],
            "Tolima-Purificacion": ["Carrera 6 # 5 - 38"],
            "Tolima-Saldaña": ["Calle 18 #17-44"],
            "Valle Del Cauca-Alcala": ["Calle 5 #7-21"],
            "Valle Del Cauca-Andalucia": ["Carrera 5 #13 - 06"],
            "Valle Del Cauca-Ansermanuevo": ["Carrera 4"],
            "Valle Del Cauca-Bugalagrande": ["Carrera 5 #5-52"],
            "Valle Del Cauca-Caicedonia": ["Carrera 16 #12-29"],
            "Valle Del Cauca-Cali": ["Carrera 15 # 51 - 40"],
            "Valle Del Cauca-Cartago": ["Cartago, Valle del Cauca, Colombia"],
            "Valle Del Cauca-El Cerrito": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-El Dovio": ["Calle 7 #7 -20"],
            "Valle Del Cauca-Florida": ["Calle 7 #17-26"],
            "Valle Del Cauca-Ginebra": ["Calle 5 #2-42"],
            "Valle Del Cauca-Guacari": ["Carrera 7 #4 - 67"],
            "Valle Del Cauca-Guadalajara De Buga": ["Carrera 8 A Calle 8 Sur Esquina"],
            "Valle Del Cauca-Jamundi": ["Carrera 2 #10-83"],
            "Valle Del Cauca-La Union": ["Calle 15"],
            "Valle Del Cauca-La Victoria": ["Calle 9 #6 - 52"],
            "Valle Del Cauca-Obando": ["Calle 3"],
            "Valle Del Cauca-Palmira": ["Carrera 8 # 5 - 46, El Placer"],
            "Valle Del Cauca-Pradera": ["Calle 7 #21 # 11"],
            "Valle Del Cauca-Restrepo": ["Calle 11 #9-67 a 9-1"],
            "Valle Del Cauca-Riofrio": ["Calle 5"],
            "Valle Del Cauca-Roldanillo": ["Carrera 7 No 7 - 51, Alcaldía Municipal"],
            "Valle Del Cauca-San Pedro": ["Carrera 6 #350"],
            "Valle Del Cauca-Sevilla": ["Carrera 50 #50 - 20"],
            "Valle Del Cauca-Toro": ["Calle 9 #3 - 13"],
            "Valle Del Cauca-Trujillo": ["Carrera 20 #21 - 02"],
            "Valle Del Cauca-Tulua": ["Calle 28 #21 - 10"],
            "Valle Del Cauca-Yotoco": ["Carrera 5 #4-54"],
            "Valle Del Cauca-Yumbo": ["Carrera 5 #9-39"],
            "Valle Del Cauca-Zarzal": ["Calle 10 #13-69"],
            }
        }
    };

    function createCityDropdown(ciudades) {
        const cityDropdown = document.createElement('select');
        cityDropdown.addEventListener('change', function() {
            const selectedCity = this.value;
            const addresses = document.querySelector(`#${this.parentElement.id} .addresses`);
            addresses.innerHTML = '';

            if (selectedCity) {
                ciudades[selectedCity].forEach(address => {
                    const addressItem = document.createElement('li');
                    addressItem.textContent = address;
                    addresses.appendChild(addressItem);
                });
            }
        });

        const defaultOption = document.createElement('option');
        defaultOption.textContent = 'Selecciona una ciudad';
        defaultOption.value = '';
        cityDropdown.appendChild(defaultOption);

        for (const ciudad in ciudades) {
            const cityOption = document.createElement('option');
            cityOption.textContent = ciudad;
            cityOption.value = ciudad;
            cityDropdown.appendChild(cityOption);
        }

        return cityDropdown;
    }

    for (const market in supermercados) {
        const container = document.getElementById(`${market}-cities`);
        const cityDiv = document.createElement('div');
        cityDiv.id = `${market}-city`;
        cityDiv.className = 'city';
        const cityDropdown = createCityDropdown(supermercados[market].ciudades);
        const addressList = document.createElement('ul');
        addressList.className = 'addresses';

        cityDiv.appendChild(cityDropdown);
        cityDiv.appendChild(addressList);
        container.appendChild(cityDiv);
    }
});


document.getElementById("comentariosForm").addEventListener("submit", function (event) {
    event.preventDefault();

    let formData = new FormData(this);

    fetch("paginaprincipal.php", {
        method: "POST",
        body: formData
    })
    .then(response => response.text())
    .then(data => {
        document.getElementById("respuesta").innerHTML = data;
        this.reset();
    })
    .catch(error => console.error("Error:", error));
});

document.getElementById('registrationForm').addEventListener('submit', function(event) {
    var contrasena = document.getElementById('contrasena').value;
    var repetirContrasena = document.getElementById('repetircontrasena').value;
    var errorContrasena = document.getElementById('errorContrasena');

    if (contrasena !== repetirContrasena) {
        event.preventDefault(); // Previene el envío del formulario
        errorContrasena.style.display = 'block'; // Muestra el mensaje de error
    } else {
        errorContrasena.style.display = 'none'; // Oculta el mensaje de error si las contraseñas coinciden
    }
});



